image: python:3.7.4-alpine3.10

pipelines:
  branches:
    "development":
      - step:
          name: Build with Docker
          deployment: Dev
          script:
            - pip3 install awscli
            - TAG=${BITBUCKET_BRANCH:-$BITBUCKET_BUILD_NUMBER}
            - aws configure set aws_access_key_id "${AWS_KEY}"
            - aws configure set aws_secret_access_key "${AWS_SECRET}"
            - eval $(aws ecr get-login --no-include-email --region us-east-2 | sed 's;https://;;g')
            - docker build -t ${IMAGE}:$TAG .
            - docker push ${IMAGE}:$TAG
          caches:
            - pip
          services:
            - docker